CREATE TYPE "product_type_enum" AS ENUM (
    'RAW_MATERIAL',
    'SEMI_FINISHED',
    'FINISHED_PRODUCT'
    );

CREATE TYPE "orders_status" AS ENUM (
    'WAITTING',
    'PROCESSING',
	'DISPATCHED',
    'DELIVERING',
    'DONE',
    'DAMAGED',
    'CANCLED'
    );

CREATE TYPE "log_batches_enum" AS ENUM (
    'PROCESSING',
	'WAITING_TO_CONFIRM',
    'DONE',
	'WAITING_TO_CANCLE',
    'EXPIRED',
    'DAMAGED'
    );

CREATE TYPE "log_batches_type" AS ENUM (
    'PRODUCTION',
    'PURCHASE'
    );

CREATE TYPE "inventories_type" AS ENUM (
    'IMPORT',
    'EXPORT'
    );

CREATE TYPE "receipt_status" AS ENUM (
  'DRAFT',
  'COMPLETED',
  'CANCELLED'
);

CREATE TABLE "roles" (
                         "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "role_name" varchar
);

CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar,
                         "password" varchar,
                         "full_name" varchar,
                         "role_id" int,
                         "store_id" int
);

CREATE TABLE "stores" (
                          "store_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "store_name" varchar,
                          "address" varchar,
                          "phone" varchar
);

CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "product_name" varchar,
                            "product_type" product_type_enum,
                            "unit" varchar,
                            "shelf_life_days" int
);

CREATE TABLE "recipes" (
                           "recipe_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "product_id" int,
                           "recipe_name" varchar,
                           "yield_quantity" float,
                           "description" text
);

CREATE TABLE "recipe_details" (
                                  "recipe_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "recipe_id" int,
                                  "raw_material_id" int,
                                  "quantity" float
);

CREATE TABLE "production_plans" (
                                    "plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "plan_date" date,
                                    "start_date" date,
                                    "end_date" date,
                                    "status" varchar,
                                    "note" text
);

CREATE TABLE "production_plan_details" (
                                           "plan_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "plan_id" int NOT NULL,
                                           "product_id" int NOT NULL,
                                           "quantity" float NOT NULL,
                                           "note" text
);

CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "delivery_id" int,
                          "store_id" int,
                          "order_date" timestamp,
                          "status" orders_status,
                          "img" varchar,
                          "comment" varchar
);

CREATE TABLE "order_details" (
                                 "order_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "order_id" int,
                                 "product_id" int,
                                 "quantity" float
);

CREATE TABLE "log_batches" (
                               "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "plan_id" int,
                               "product_id" int,
                               "quantity" float,
                               "production_date" date,
                               "expiry_date" date,
                               "status" log_batches_enum,
                               "type" log_batches_type,
                               "created_at" timestamp
);

CREATE TABLE "inventories" (
                               "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "product_id" int,
                               "batch_id" int,
                               "quantity" float,
                               "expiry_date" date
);

CREATE TABLE "inventory_transactions" (
                                          "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "product_id" int,
                                          "batch_id" int,
                                          "type" inventories_type,
                                          "quantity" float,
                                          "created_at" timestamp,
                                          "note" text,
                                          "receipt_id" int
);

CREATE TABLE "deliveries" (
                              "delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "delivery_date" date,
                              "shipper_id" int,
                              "created_at" timestamp
);

CREATE TABLE "quality_feedbacks" (
                                     "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_id" int unique,
                                     "rating" int,
                                     "comment" text,
                                     "created_at" timestamp
);

CREATE TABLE "reports" (
                           "report_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "report_type" varchar,
                           "user_id" int,
                           "created_date" timestamp
);

CREATE TABLE "receipts" (
                            "receipt_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "receipt_code" varchar,
                            "order_id" int,
                            "export_date" timestamp DEFAULT (now()),
                            "status" receipt_status,
                            "note" text
);

CREATE TABLE "order_detail_fill" (
                                     "fill_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_detail_id" int NOT NULL,
                                     "batch_id" int NOT NULL,
                                     "quantity" float NOT NULL,
                                     "created_at" timestamp
);

COMMENT ON COLUMN "roles"."role_name" IS 'ADMIN, MANAGER, STORE, SUPPLY_COORDINATOR, WAREHOUSE_KEEPER, SHIPPER';

COMMENT ON COLUMN "users"."store_id" IS 'Unique';

COMMENT ON COLUMN "products"."shelf_life_days" IS 'sản phẩm có thời gian sủ dụng bao ngày (ex: 30 days)';

COMMENT ON COLUMN "recipes"."yield_quantity" IS 'How much this recipe makes';

COMMENT ON COLUMN "log_batches"."production_date" IS 'có thể là ngày sản xuất hoặc ngày nhập hàng';

COMMENT ON COLUMN "inventory_transactions"."receipt_id" IS 'Dòng biến động này thuộc phiếu xuất nào?';

COMMENT ON COLUMN "receipts"."receipt_code" IS 'Mã phiếu, VD: PXK-001';

COMMENT ON COLUMN "receipts"."status" IS 'DRAFT (Đang soạn), COMPLETED (Đã trừ kho), CANCELLED';

ALTER TABLE "receipts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("receipt_id") REFERENCES "receipts" ("receipt_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("order_detail_id") REFERENCES "order_details" ("order_detail_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "users" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "recipes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("recipe_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("raw_material_id") REFERENCES "products" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "log_batches" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");

-- ALTER TABLE "products" ADD FOREIGN KEY ("product_id") REFERENCES "log_batches" ("product_id");
ALTER TABLE "log_batches" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

-- ALTER TABLE "log_batches" ADD FOREIGN KEY ("batch_id") REFERENCES "inventories" ("batch_id");
ALTER TABLE "inventories" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("delivery_id");

-- ALTER TABLE "orders" ADD FOREIGN KEY ("order_id") REFERENCES "quality_feedbacks" ("order_id");
ALTER TABLE "quality_feedbacks" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "deliveries" ADD FOREIGN KEY ("shipper_id") REFERENCES "users" ("user_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");


/*=========================================================================================================*/
/*=========================================================================================================*/
/*=============================================ADDING MOCK DATA============================================*/
/*=========================================================================================================*/
/*=========================================================================================================*/

BEGIN;

-- =============================
-- ROLES
-- =============================
INSERT INTO roles(role_name) VALUES
('ADMIN'),
('MANAGER'),
('STORE'),
('SUPPLY_COORDINATOR'),
('WAREHOUSE_KEEPER'),
('SHIPPER');

-- =============================
-- STORES
-- =============================
INSERT INTO stores(store_name,address,phone)
SELECT
'Store ' || i,
'Address ' || i,
'090000' || LPAD(i::text,3,'0')
FROM generate_series(1,15) i;

-- =============================
-- USERS
-- =============================

-- Admin
INSERT INTO users(username,password,full_name,role_id)
VALUES ('admin','123','System Admin',1);

-- Managers
INSERT INTO users(username,password,full_name,role_id)
SELECT
'manager'||i,
'123',
'Manager '||i,
2
FROM generate_series(1,5) i;

-- Store users
INSERT INTO users(username,password,full_name,role_id,store_id)
SELECT
'store_user'||i,
'123',
'Store User '||i,
3,
(i % 15)+1
FROM generate_series(1,30) i;

-- Supply coordinators
INSERT INTO users(username,password,full_name,role_id)
SELECT
'supply'||i,
'123',
'Supply Coordinator '||i,
4
FROM generate_series(1,5) i;

-- Warehouse keepers
INSERT INTO users(username,password,full_name,role_id)
SELECT
'warehouse'||i,
'123',
'Warehouse Keeper '||i,
5
FROM generate_series(1,10) i;

-- Shippers
INSERT INTO users(username,password,full_name,role_id)
SELECT
'shipper'||i,
'123',
'Shipper '||i,
6
FROM generate_series(1,10) i;

-- =============================
-- PRODUCTS
-- =============================

-- RAW MATERIAL
INSERT INTO products(product_name,product_type,unit,shelf_life_days)
SELECT
'Raw Material '||i,
'RAW_MATERIAL',
'kg',
180
FROM generate_series(1,10) i;

-- SEMI FINISHED
INSERT INTO products(product_name,product_type,unit,shelf_life_days)
SELECT
'Semi Product '||i,
'SEMI_FINISHED',
'kg',
10
FROM generate_series(1,5) i;

-- FINISHED PRODUCTS
INSERT INTO products(product_name,product_type,unit,shelf_life_days)
SELECT
'Cake Product '||i,
'FINISHED_PRODUCT',
'piece',
3
FROM generate_series(1,10) i;

-- =============================
-- RECIPES
-- =============================

INSERT INTO recipes(product_id,recipe_name,yield_quantity,description)
SELECT
i,
'Recipe '||i,
10,
'Recipe description'
FROM generate_series(16,25) i;

-- =============================
-- RECIPE DETAILS
-- =============================

INSERT INTO recipe_details(recipe_id,raw_material_id,quantity)
SELECT
r.recipe_id,
((random()*9)+1)::int,
(random()*5)+1
FROM recipes r
CROSS JOIN generate_series(1,5);

-- =============================
-- PRODUCTION PLANS
-- =============================

INSERT INTO production_plans(plan_date,start_date,end_date,status,note)
SELECT
CURRENT_DATE - (i*2),
CURRENT_DATE - (i*2),
CURRENT_DATE - (i*2) + 1,
CASE
WHEN i%3=0 THEN 'DONE'
WHEN i%3=1 THEN 'PROCESSING'
ELSE 'PLANNED'
END,
'Production plan '||i
FROM generate_series(1,20) i;

-- =============================
-- PLAN DETAILS
-- =============================

INSERT INTO production_plan_details(plan_id,product_id,quantity,note)
SELECT
p.plan_id,
((random()*9)+16)::int,
(random()*200)+50,
'Production item'
FROM production_plans p
CROSS JOIN generate_series(1,3);

-- =============================
-- LOG BATCHES
-- =============================

INSERT INTO log_batches(
plan_id,
product_id,
quantity,
production_date,
expiry_date,
status,
type,
created_at
)
SELECT
((random()*19)+1)::int,
((random()*9)+16)::int,
(random()*100)+10,
CURRENT_DATE - ((random()*10)::int),
CURRENT_DATE + ((random()*5)::int),
(ARRAY[
'PROCESSING',
'WAITING_TO_CONFIRM',
'DONE',
'WAITING_TO_CANCLE',
'EXPIRED',
'DAMAGED'
])[floor(random()*6)+1]::log_batches_enum,
(ARRAY['PRODUCTION','PURCHASE'])[floor(random()*2)+1]::log_batches_type,
now()
FROM generate_series(1,200);

-- =============================
-- INVENTORIES
-- =============================

INSERT INTO inventories(product_id,batch_id,quantity,expiry_date)
SELECT
product_id,
batch_id,
quantity,
expiry_date
FROM log_batches;

-- =============================
-- DELIVERIES
-- =============================

INSERT INTO deliveries(delivery_date,shipper_id,created_at)
SELECT
CURRENT_DATE - (random()*10)::int,
((random()*9)+50)::int,
now()
FROM generate_series(1,100);

-- =============================
-- ORDERS
-- =============================

INSERT INTO orders(delivery_id,store_id,order_date,status,img,comment)
SELECT
((random()*99)+1)::int,
((random()*14)+1)::int,
now() - (random()*10)*interval '1 day',
(ARRAY[
'WAITTING',
'PROCESSING',
'DISPATCHED',
'DELIVERING',
'DONE',
'DAMAGED',
'CANCLED'
])[floor(random()*7)+1]::orders_status,
NULL,
'Customer order'
FROM generate_series(1,200);

-- =============================
-- ORDER DETAILS
-- =============================

INSERT INTO order_details(order_id,product_id,quantity)
SELECT
o.order_id,
((random()*9)+16)::int,
(random()*10)+1
FROM orders o
CROSS JOIN generate_series(1,3);

-- =============================
-- RECEIPTS
-- =============================

INSERT INTO receipts(receipt_code,order_id,status,note)
SELECT
'PXK-'||LPAD(order_id::text,4,'0'),
order_id,
(ARRAY['DRAFT','COMPLETED','CANCELLED'])[floor(random()*3)+1]::receipt_status,
'Warehouse export'
FROM orders;

-- =============================
-- INVENTORY TRANSACTIONS
-- =============================

INSERT INTO inventory_transactions(
product_id,
batch_id,
type,
quantity,
created_at,
note,
receipt_id
)
SELECT
((random()*9)+16)::int,
((random()*199)+1)::int,
(ARRAY['IMPORT','EXPORT'])[floor(random()*2)+1]::inventories_type,
(random()*20)+1,
now(),
'Inventory movement',
((random()*199)+1)::int
FROM generate_series(1,500);

-- =============================
-- ORDER DETAIL FILL
-- =============================

INSERT INTO order_detail_fill(order_detail_id,batch_id,quantity,created_at)
SELECT
order_detail_id,
((random()*199)+1)::int,
(random()*5)+1,
now()
FROM order_details;

-- =============================
-- FEEDBACK
-- =============================

INSERT INTO quality_feedbacks(order_id,rating,comment,created_at)
SELECT
order_id,
((random()*4)+1)::int,
'Customer feedback',
now()
FROM orders
WHERE status='DONE'
LIMIT 50;

COMMIT;

/*=========================================================================================================*/
/*=========================================================================================================*/
/*=============================================ADDING MOCK DATA============================================*/
/*=========================================================================================================*/
/*=========================================================================================================*/


/*=========================================================================================================*/
--CODE FOR RESET DATABASE POSTGRESQL
-- 1. Xóa sổ toàn bộ Schema public (bao gồm mọi Table, View, Type,...)
DROP SCHEMA public CASCADE;

-- 2. Tạo lại Schema public mới trắng tinh
CREATE SCHEMA public;

-- 3. Cấp lại quyền truy cập cho user của bạn (User trong ảnh bạn gửi)
GRANT ALL ON SCHEMA public TO public;
GRANT ALL ON SCHEMA public TO central_kitchen_user;
/*=========================================================================================================*/