-- select * from orders

-- select * from products

-- select * from stores

-- select * from order_details

-- select * from order_detail_fill

-- select * from deliveries

-- select * from users

-- select * from receipts

/*=========================================================================================================*/
--CODE FOR RESET DATABASE POSTGRESQL
-- 1. Xóa sổ toàn bộ Schema public (bao gồm mọi Table, View, Type,...)
BEGIN;

DROP SCHEMA public CASCADE;

-- 2. Tạo lại Schema public mới trắng tinh
CREATE SCHEMA public;

-- 3. Cấp lại quyền truy cập cho user của bạn (User trong ảnh bạn gửi)
GRANT ALL ON SCHEMA public TO public;
-- GRANT ALL ON SCHEMA public TO central_kitchen_user;
GRANT ALL ON SCHEMA public TO kitchencontroldb_user;

COMMIT;
/*=========================================================================================================*/


CREATE TYPE "product_type_enum" AS ENUM (
    'RAW_MATERIAL',
    'MAIN',
	'SIDE',
	'BEVERAGE',
	'DESSERT',
	'SAUCE'
    );

CREATE TYPE "orders_status" AS ENUM (
    'WAITING',
    'PROCESSING',
	'DISPATCHED',
    'DELIVERING',
	'PARTIAL_DELIVERED',
    'DONE',
    'DAMAGED',
    'CANCELED'
    );

CREATE TYPE "log_batches_enum" AS ENUM (
    'PROCESSING',
	'WAITING_TO_CONFIRM',
    'DONE',
	'WAITING_TO_CANCEL',
    'DAMAGED'
    );

CREATE TYPE "log_batches_type" AS ENUM (
    'PRODUCTION',
    'PURCHASE'
    );

CREATE TYPE "inventories_type" AS ENUM (
    'IMPORT',
    'EXPORT'
    );

CREATE TYPE "receipt_status" AS ENUM (
  'READY',
  'COMPLETED'
);

CREATE TYPE "deliveries_status" AS ENUM (
    'WAITING',
    'DELIVERING',
	'DONE',
	'CANCEL'
    );

CREATE TYPE "production_plan_status" AS ENUM (
	'DRAFT',
	'WAITING',
    'PROCESSING',
	'COMPLETE_ONE_SECTION',
	'DONE',
	'CANCEL'
    );

CREATE TABLE "roles" (
                         "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "role_name" varchar
);

CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar,
                         "password" varchar,
                         "full_name" varchar,
                         "role_id" int,
                         "store_id" int
);

CREATE TABLE "stores" (
                          "store_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "store_name" varchar,
                          "address" varchar,
                          "phone" varchar
);

CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "product_name" varchar,
                            "product_type" product_type_enum,
                            "unit" varchar,
							"price" float,
                            "shelf_life_days" int
);

CREATE TABLE "recipes" (
                           "recipe_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "product_id" int,
                           "recipe_name" varchar,
                           "yield_quantity" float,
                           "description" text
);

CREATE TABLE "recipe_details" (
                                  "recipe_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "recipe_id" int,
                                  "raw_material_id" int,
                                  "quantity" float
);

CREATE TABLE "production_plans" (
                                    "plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "plan_date" date,
                                    "start_date" date,
                                    "end_date" date,
                                    "status" production_plan_status,
                                    "note" text
);

CREATE TABLE "production_plan_details" (
                                           "plan_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "plan_id" int NOT NULL,
                                           "product_id" int NOT NULL,
                                           "quantity" float NOT NULL,
                                           "note" text
);

CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						  "parent_order_id" int,
                          "delivery_id" int,
                          "store_id" int,
                          "order_date" timestamp,
						  "type" varchar,
                          "status" orders_status,
                          "img" varchar,
                          "comment" varchar
);

CREATE TABLE "order_details" (
                                 "order_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "order_id" int,
                                 "product_id" int,
                                 "quantity" float
);

CREATE TABLE "log_batches" (
                               "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "plan_id" int,
                               "product_id" int,
                               "quantity" float,
                               "production_date" date,
                               "expiry_date" date,
                               "status" log_batches_enum,
                               "type" log_batches_type,
                               "created_at" timestamp
);

CREATE TABLE "inventories" (
                               "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "product_id" int,
                               "batch_id" int UNIQUE,
                               "quantity" float,
                               "expiry_date" date
);

CREATE TABLE "inventory_transactions" (
                                          "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "product_id" int,
                                          "batch_id" int,
                                          "type" inventories_type,
                                          "quantity" float,
                                          "created_at" timestamp,
                                          "note" text,
                                          "receipt_id" int
);

CREATE TABLE "deliveries" (
                              "delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "delivery_date" date,
                              "shipper_id" int,
							  "status" deliveries_status,
                              "created_at" timestamp
);

CREATE TABLE "quality_feedbacks" (
                                     "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_id" int unique,
                                     "rating" int,
                                     "comment" text,
                                     "created_at" timestamp
);

-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- OLD
-- CREATE TABLE "reports" (
--                            "report_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--                            "report_type" varchar,
--                            "user_id" int,
--                            "created_date" timestamp
-- );

-- NEW
CREATE TABLE "waste_logs" (
					    "waste_id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					    "product_id" int,
					    "batch_id"   int,
					    "quantity"   float,
					    "waste_type" varchar, -- 'EXPIRED', 'DAMAGED_SHIPPING'
					    "order_id"   int,
					    "note"       varchar,
					    "created_at" timestamp
);
-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

CREATE TABLE "receipts" (
                            "receipt_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "receipt_code" varchar,
                            "order_id" int UNIQUE,
                            "export_date" timestamp DEFAULT (now()),
                            "status" receipt_status,
                            "note" text
);

CREATE TABLE "order_detail_fill" (
                                     "fill_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_detail_id" int NOT NULL,
                                     "batch_id" int NOT NULL,
                                     "quantity" float NOT NULL,
                                     "created_at" timestamp
);

COMMENT ON COLUMN "roles"."role_name" IS 'ADMIN, MANAGER, STORE, SUPPLY_COORDINATOR, WAREHOUSE_KEEPER, SHIPPER';

COMMENT ON COLUMN "users"."store_id" IS 'Unique';

COMMENT ON COLUMN "products"."shelf_life_days" IS 'sản phẩm có thời gian sủ dụng bao ngày (ex: 30 days)';

COMMENT ON COLUMN "recipes"."yield_quantity" IS 'How much this recipe makes';

COMMENT ON COLUMN "log_batches"."production_date" IS 'có thể là ngày sản xuất hoặc ngày nhập hàng';

COMMENT ON COLUMN "inventory_transactions"."receipt_id" IS 'Dòng biến động này thuộc phiếu xuất nào?';

COMMENT ON COLUMN "receipts"."receipt_code" IS 'Mã phiếu, VD: PXK-001';

COMMENT ON COLUMN "receipts"."status" IS 'DRAFT (Đang soạn), COMPLETED (Đã trừ kho), CANCELLED';

ALTER TABLE "receipts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("receipt_id") REFERENCES "receipts" ("receipt_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("order_detail_id") REFERENCES "order_details" ("order_detail_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "users" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "recipes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("recipe_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("raw_material_id") REFERENCES "products" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "log_batches" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");

-- ALTER TABLE "products" ADD FOREIGN KEY ("product_id") REFERENCES "log_batches" ("product_id");
ALTER TABLE "log_batches" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

-- ALTER TABLE "log_batches" ADD FOREIGN KEY ("batch_id") REFERENCES "inventories" ("batch_id");
ALTER TABLE "inventories" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("delivery_id");

-- ALTER TABLE "orders" ADD FOREIGN KEY ("order_id") REFERENCES "quality_feedbacks" ("order_id");
ALTER TABLE "quality_feedbacks" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- OLD
-- ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

-- NEW
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("batch_id")   REFERENCES "log_batches" ("batch_id");
ALTER TABLE "waste_logs" ADD FOREIGN KEY ("order_id")   REFERENCES "orders" ("order_id");
-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

ALTER TABLE "deliveries" ADD FOREIGN KEY ("shipper_id") REFERENCES "users" ("user_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");


/*==============================================================================================================================================================*/
/*==============================================================================================================================================================*/
/*==================================================================ADDING MOCK DATA============================================================================*/
/*==============================================================================================================================================================*/
/*==============================================================================================================================================================*/
BEGIN;

-- ============================================
-- ROLES
-- ============================================
INSERT INTO roles (role_name) VALUES 
('ADMIN'),                    -- 1: Quản trị hệ thống
('MANAGER'),                  -- 2: Quản lý
('STORE'),                    -- 3: Nhân viên cửa hàng
('SUPPLY_COORDINATOR'),       -- 4: Điều phối cung ứng
('WAREHOUSE_KEEPER'),         -- 5: Thủ kho
('SHIPPER'),                  -- 6: Nhân viên giao hàng
('KITCHEN_STAFF');            -- 7: Nhân viên bếp

-- =============================
-- STORES
-- =============================
INSERT INTO stores(store_name,address,phone) VALUES
('Store District 1', '12 Nguyen Hue',       '090000001'),  -- store_id = 1
('Store District 2', '22 Tran Nao',         '090000002'),  -- store_id = 2
('Store District 3', '45 Vo Van Tan',       '090000003'),  -- store_id = 3
('Store District 5', '19 Tran Hung Dao',    '090000004'),  -- store_id = 4
('Store District 7', '88 Nguyen Thi Thap',  '090000005');  -- store_id = 5

-- =============================
-- USERS
-- =============================
INSERT INTO users(username,password,full_name,role_id,store_id) VALUES
('admin',      '1', 'System Admin',          1, NULL),  -- user_id=1,  ADMIN, không gắn store
('manager',   '1', 'Manager Nguyen',         2, NULL),  -- user_id=2,  MANAGER
('store1',     '1', 'Store Staff 1',          3, 1),     -- user_id=3,  STORE → store_id=1
('store2',     '1', 'Store Staff 2',          3, 2),     -- user_id=4,  STORE → store_id=2
('store3',     '1', 'Store Staff 3',          3, 3),     -- user_id=5,  STORE → store_id=3
('store4',     '1', 'Store Staff 5',          3, 4),     -- user_id=6,  STORE → store_id=4
('store5',     '1', 'Store Staff 7',          3, 5),     -- user_id=7,  STORE → store_id=5
('supply',    '1', 'Supply Coordinator A',   4, NULL),  -- user_id=8,  SUPPLY_COORDINATOR
('warehouse', '1', 'Warehouse Keeper A',     5, NULL),  -- user_id=9, WAREHOUSE_KEEPER
('kitchen',   '1', 'Kitchen Manager A',     7, NULL),  -- user_id=10, KITCHEN_MANAGER
('shipper1',   '1', 'Shipper A',              6, NULL),  -- user_id=11, SHIPPER
('shipper2',   '1', 'Shipper B',              6, NULL),  -- user_id=12, SHIPPER
('shipper3',   '1', 'Shipper C',              6, NULL),  -- user_id=13, SHIPPER
('shipper4',   '1', 'Shipper D',              6, NULL),  -- user_id=14, SHIPPER
('shipper5',   '1', 'Shipper D',              6, NULL);  -- user_id=15, SHIPPER

-- =============================
-- PRODUCTS
-- =============================
INSERT INTO products(product_name,product_type,unit,price,shelf_life_days) VALUES
-- RAW MATERIALS
('Flour',             'RAW_MATERIAL',  'kg',     15000,  365),
('Sugar',             'RAW_MATERIAL',  'kg',     20000,  365),
('Milk',              'RAW_MATERIAL',  'liter',  25000,  365),
('Butter',            'RAW_MATERIAL',  'kg',     80000,  365),
('Chocolate',         'RAW_MATERIAL',  'kg',     120000, 365),

-- SEMI-FINISHED
('Cake Base',         'RAW_MATERIAL', 'piece',  30000,  365),
('Cream Mix',         'RAW_MATERIAL', 'kg',     50000,  365),
('Chocolate Filling', 'RAW_MATERIAL', 'kg',     60000,  365),

-- [FIX] Đổi 'FINISHED_PRODUCT' → type hợp lệ trong enum.
-- Các sản phẩm bánh ngọt dùng 'DESSERT', thêm price cho tất cả
('Strawberry Cake',   'DESSERT',       'piece',  85000,  365),
('Chocolate Cake',    'DESSERT',       'piece',  90000,  365),
('Tiramisu',          'DESSERT',       'piece',  95000,  365),
('Matcha Cake',       'DESSERT',       'piece',  85000,  365),
('Cupcake',           'DESSERT',       'piece',  45000,  365),
('Cheesecake',        'DESSERT',       'piece',  80000,  365),
('Croissant',         'MAIN',          'piece',  35000,  365),
-- [NEW MOCK DATA] Thêm các sản phẩm đại diện (với shelf_life_days > 100)
('Chicken Thigh',          'RAW_MATERIAL', 'kg',    60000,  150), -- 16
('Coca Cola',              'BEVERAGE',     'can',   15000,  150), -- 17
('Garlic Sauce',           'SAUCE',        'liter', 40000,  150), -- 18
('Grilled Chicken Rice',   'MAIN',         'box',   55000,  150), -- 19
('Mashed Potato',          'SIDE',         'box',   30000,  150), -- 20
('Mango Pudding',          'DESSERT',      'piece', 25000,  150), -- 21
-- [EXTENDED MOCK DATA] Thêm nguyên liệu thô và 10 món mới
('Beef',                   'RAW_MATERIAL', 'kg',    150000, 150), -- 22
('Pasta',                  'RAW_MATERIAL', 'kg',    30000,  150), -- 23
('Tomato Sauce',           'SAUCE',        'liter', 25000,  150), -- 24
('Pizza Dough',            'RAW_MATERIAL', 'piece', 15000,  150), -- 25
('Cheese',                 'RAW_MATERIAL', 'kg',    180000, 150), -- 26
('Potato',                 'RAW_MATERIAL', 'kg',    20000,  150), -- 27
('Bread',                  'RAW_MATERIAL', 'piece', 5000,   150), -- 28
('Coffee Bean',            'RAW_MATERIAL', 'kg',    250000, 150), -- 29
('Chicken Wings',          'RAW_MATERIAL', 'kg',    70000,  150), -- 30
('Beef Steak',             'MAIN',         'box',   120000, 150), -- 31
('Spaghetti Bolognese',    'MAIN',         'box',   65000,  150), -- 32
('Margherita Pizza',       'MAIN',         'box',   85000,  150), -- 33
('Chicken Burger',         'MAIN',         'box',   45000,  150), -- 34
('French Fries',           'SIDE',         'box',   25000,  150), -- 35
('Garlic Bread',           'SIDE',         'box',   20000,  150), -- 36
('Fried Chicken Wings',    'SIDE',         'box',   40000,  150), -- 37
('Pepsi',                  'BEVERAGE',     'can',   15000,  150), -- 38
('Orange Juice',           'BEVERAGE',     'cup',   25000,  150), -- 39
('Iced Latte',             'BEVERAGE',     'cup',   35000,  150); -- 40

-- =============================
-- RECIPES
-- =============================
INSERT INTO recipes(product_id,recipe_name,yield_quantity,description) VALUES
(6,  'Cake Base Recipe',         20, 'Base dough for layered cakes'),           -- recipe_id=1
(7,  'Cream Mix Recipe',         10, 'Whipped cream mixture'),                  -- recipe_id=2
(8,  'Chocolate Filling Recipe', 10, 'Chocolate ganache filling'),              -- recipe_id=3
(9,  'Strawberry Cake Recipe',   10, 'Strawberry cake using Cake Base & Cream'),-- recipe_id=4
(10, 'Chocolate Cake Recipe',    10, 'Chocolate cake with chocolate filling'),  -- recipe_id=5
(11, 'Tiramisu Recipe',           8, 'Italian dessert with cream mix'),         -- recipe_id=6
(12, 'Matcha Cake Recipe',       10, 'Matcha cake using Cake Base & Cream'),    -- recipe_id=7
(13, 'Cupcake Recipe',           20, 'Small cupcake with cream topping'),       -- recipe_id=8
(14, 'Cheesecake Recipe',        10, 'Classic cheesecake'),                     -- recipe_id=9
(15, 'Croissant Recipe',         20, 'Buttery croissant'),                      -- recipe_id=10
-- [NEW MOCK DATA] Công thức chế biến cho các món tự nấu 
(18, 'Garlic Sauce Recipe',         10, 'Nấu sốt tỏi ngọt'),                           -- recipe_id = 11
(19, 'Grilled Chicken Rice Recipe', 10, 'Cơm gà nướng với đùi gà và sốt tỏi'),         -- recipe_id = 12
(20, 'Mashed Potato Recipe',        10, 'Khoai tây nghiền với bơ sữa'),                -- recipe_id = 13
(21, 'Mango Pudding Recipe',        10, 'Pudding xoài thơm béo'),                      -- recipe_id = 14
-- [EXTENDED MOCK DATA] Công thức cho các món mới
(31, 'Beef Steak Recipe',           10, 'Beef Steak nấu bơ'),                          -- recipe_id = 15
(32, 'Spaghetti Bolognese Recipe',  10, 'Mì ý bò băm sốt cà chua'),                    -- recipe_id = 16
(33, 'Margherita Pizza Recipe',     10, 'Pizza phô mai cơ bản'),                       -- recipe_id = 17
(34, 'Chicken Burger Recipe',       10, 'Burger gà phô mai'),                          -- recipe_id = 18
(35, 'French Fries Recipe',         10, 'Khoai tây chiên'),                            -- recipe_id = 19
(36, 'Garlic Bread Recipe',         10, 'Bánh mì nướng bơ tỏi'),                       -- recipe_id = 20
(37, 'Fried Chicken Wings Recipe',  10, 'Cánh gà chiên giòn'),                         -- recipe_id = 21
(40, 'Iced Latte Recipe',           10, 'Cà phê sữa đá pha từ hạt');                   -- recipe_id = 22

-- =============================
-- RECIPE DETAILS
-- =============================
INSERT INTO recipe_details(recipe_id,raw_material_id,quantity) VALUES
(1, 1, 5.0),   -- Cake Base dùng Flour: 5 kg
(1, 2, 2.0),   -- Cake Base dùng Sugar: 2 kg
(1, 4, 1.0),   -- Cake Base dùng Butter: 1 kg
-- Recipe 2: Cream Mix (product_id=7) — dùng RAW MATERIAL
(2, 3, 3.0),   -- Cream Mix dùng Milk: 3 liter
(2, 2, 1.0),   -- Cream Mix dùng Sugar: 1 kg
-- Recipe 3: Chocolate Filling (product_id=8) — dùng RAW MATERIAL
(3, 5, 3.0),   -- Chocolate Filling dùng Chocolate: 3 kg
(3, 3, 1.0),   -- Chocolate Filling dùng Milk: 1 liter
-- Recipe 4: Strawberry Cake (product_id=9) — dùng SEMI_FINISHED
(4, 6, 2.0),   -- Strawberry Cake dùng Cake Base: 2 piece
(4, 7, 1.0),   -- Strawberry Cake dùng Cream Mix: 1 kg
-- Recipe 5: Chocolate Cake (product_id=10) — dùng SEMI_FINISHED
(5, 6, 2.0),   -- Chocolate Cake dùng Cake Base: 2 piece
(5, 8, 1.5),   -- Chocolate Cake dùng Chocolate Filling: 1.5 kg
-- Recipe 6: Tiramisu (product_id=11) — dùng SEMI_FINISHED + RAW
(6, 7, 2.0),   -- Tiramisu dùng Cream Mix: 2 kg
(6, 2, 0.5),   -- Tiramisu dùng Sugar: 0.5 kg
-- Recipe 7: Matcha Cake (product_id=12) — dùng SEMI_FINISHED
(7, 6, 2.0),   -- Matcha Cake dùng Cake Base: 2 piece
(7, 7, 1.0),   -- Matcha Cake dùng Cream Mix: 1 kg
-- Recipe 8: Cupcake (product_id=13) — dùng RAW + SEMI_FINISHED
(8, 1, 1.0),   -- Cupcake dùng Flour: 1 kg
(8, 2, 1.0),   -- Cupcake dùng Sugar: 1 kg
(8, 7, 0.5),   -- Cupcake dùng Cream Mix: 0.5 kg
-- Recipe 9: Cheesecake (product_id=14) — dùng RAW MATERIAL
(9, 3, 2.0),   -- Cheesecake dùng Milk: 2 liter
(9, 2, 1.0),   -- Cheesecake dùng Sugar: 1 kg
(9, 4, 0.5),   -- Cheesecake dùng Butter: 0.5 kg
-- Recipe 10: Croissant (product_id=15) — dùng RAW MATERIAL
(10, 1, 3.0),  -- Croissant dùng Flour: 3 kg
(10, 4, 2.0),  -- Croissant dùng Butter: 2 kg
(10, 2, 0.5),  -- Croissant dùng Sugar: 0.5 kg
-- [NEW MOCK DATA] Vật liệu tiêu hao cho công thức mới
(11, 2,  1.0), -- Garlic Sauce (Recipe 11) tốn 1kg Sugar (id=2)
(12, 16, 5.0), -- Grilled Chicken Rice (Recipe 12) tốn 5kg Chicken Thigh (id=16)
(12, 18, 0.5), -- Grilled Chicken Rice (Recipe 12) tốn 0.5L Garlic Sauce (id=18)
(13, 4,  2.0), -- Mashed Potato (Recipe 13) tốn 2kg Butter (id=4)
(13, 3,  1.0), -- Mashed Potato (Recipe 13) tốn 1L Milk (id=3)
(14, 3,  2.0), -- Mango Pudding (Recipe 14) tốn 2L Milk (id=3)
(14, 2,  1.0), -- Mango Pudding (Recipe 14) tốn 1kg Sugar (id=2)
-- [EXTENDED MOCK DATA] Vật liệu tiêu hao cho 8 công thức mới
(15, 22, 5.0), -- Beef Steak (Recipe 15) tốn 5kg Beef
(15, 4,  1.0), -- Beef Steak (Recipe 15) tốn 1kg Butter
(16, 23, 2.0), -- Spaghetti (Recipe 16) tốn 2kg Pasta
(16, 22, 2.0), -- Spaghetti (Recipe 16) tốn 2kg Beef
(16, 24, 1.0), -- Spaghetti (Recipe 16) tốn 1L Tomato Sauce
(17, 25, 10.0),-- Margherita (Recipe 17) tốn 10 Đế bành
(17, 26, 2.0), -- Margherita (Recipe 17) tốn 2kg Cheese
(17, 24, 1.0), -- Margherita (Recipe 17) tốn 1L Tomato Sauce
(18, 28, 10.0),-- Chicken Burger (Recipe 18) tốn 10 Bread
(18, 26, 1.0), -- Chicken Burger (Recipe 18) tốn 1kg Cheese
(18, 16, 3.0), -- Chicken Burger (Recipe 18) tốn 3kg Chicken Thigh
(19, 27, 5.0), -- French Fries (Recipe 19) tốn 5kg Potato
(20, 28, 10.0),-- Garlic Bread (Recipe 20) tốn 10 Bread
(20, 18, 0.5), -- Garlic Bread (Recipe 20) tốn 0.5L Garlic Sauce
(21, 30, 5.0), -- Fried Chicken Wings (Recipe 21) tốn 5kg Chicken Wings
(21, 1,  1.0), -- Fried Chicken Wings (Recipe 21) tốn 1kg Flour
(22, 29, 0.5), -- Iced Latte (Recipe 22) tốn 0.5kg Coffee Bean
(22, 3,  2.0); -- Iced Latte (Recipe 22) tốn 2L Milk

-- =============================
-- PRODUCTION PLANS
-- =============================
INSERT INTO production_plans(plan_date,start_date,end_date,status,note) VALUES
('2026-03-01', '2026-03-02', '2026-03-05', 'DONE',       'Weekly production batch 1'),  -- plan_id=1
('2026-03-06', '2026-03-07', '2026-03-10', 'DONE',       'Weekly production batch 2'),  -- plan_id=2 [SỬA: PROCESSING→DONE vì các lô đã DONE]
('2026-03-11', '2026-03-12', '2026-03-14', 'DONE',       'Weekly production batch 3'),  -- plan_id=3 [SỬA: tương tự]
('2026-03-15', '2026-03-16', '2026-03-18', 'PROCESSING', 'Next batch'),                 -- plan_id=4
('2026-03-19', '2026-03-20', '2026-03-22', 'PROCESSING', 'Upcoming production'),        -- plan_id=5
-- [NEW MOCK DATA] Lên kế hoạch sản xuất cho các món tự nấu
('2026-03-20', '2026-03-21', '2026-03-22', 'DONE', 'Kế hoạch sản xuất hàng loạt mẻ đáp ứng testing (plan 6)'), -- plan_id = 6
-- [EXTENDED MOCK DATA] Kế hoạch sản xuất các món mở rộng
('2026-03-21', '2026-03-22', '2026-03-23', 'DONE', 'Sản xuất mở rộng 8 món mới (plan 7)'); -- plan_id = 7

-- =============================
-- PRODUCTION PLAN DETAILS
-- =============================
INSERT INTO production_plan_details(plan_id,product_id,quantity,note) VALUES
(1,  9, 5000, 'Strawberry Cake — plan 1'),
(1, 10, 5000, 'Chocolate Cake — plan 1'),
(2, 11, 4000, 'Tiramisu — plan 2'),
(2, 12, 6000, 'Matcha Cake — plan 2'),
(3, 13,10000, 'Cupcake — plan 3'),
(3, 14, 3000, 'Cheesecake — plan 3'),
(4, 15, 5000, 'Croissant — plan 4'),
(5,  9, 8000, 'Strawberry Cake — plan 5'),
(5, 10, 8000, 'Chocolate Cake — plan 5'),
-- [NEW MOCK DATA] Định mức số lượng sản xuất cho kế hoạch 6 (>1000 phần)
(6, 18, 1500, 'Sản xuất Sốt Tỏi'),               
(6, 19, 1500, 'Sản xuất Cơm Gà Nướng'),          
(6, 20, 1500, 'Sản xuất Khoai Tây Nghiền'),      
(6, 21, 1500, 'Sản xuất Mango Pudding'),
-- [EXTENDED MOCK DATA] Định mức sản xuất cho plan 7 (8 món)
(7, 31, 1500, 'Sản xuất Beef Steak'),
(7, 32, 1500, 'Sản xuất Spaghetti Bolognese'),
(7, 33, 1500, 'Sản xuất Margherita Pizza'),
(7, 34, 1500, 'Sản xuất Chicken Burger'),
(7, 35, 1500, 'Sản xuất French Fries'),
(7, 36, 1500, 'Sản xuất Garlic Bread'),
(7, 37, 1500, 'Sản xuất Fried Chicken Wings'),
(7, 40, 1500, 'Sản xuất Iced Latte');

-- =============================
-- LOG BATCHES
-- =============================
INSERT INTO log_batches(plan_id,product_id,quantity,production_date,expiry_date,status,type,created_at) VALUES
(1,  9, 5000,'2026-03-02','2027-03-02','DONE',       'PRODUCTION', now()),  -- batch_id=1
(1, 10, 5000,'2026-03-02','2027-03-02','DONE',       'PRODUCTION', now()),  -- batch_id=2
(2, 11, 4000,'2026-03-07','2027-03-07','DONE',       'PRODUCTION', now()),  -- batch_id=3
(2, 12, 6000,'2026-03-07','2027-03-07','DONE',       'PRODUCTION', now()),  -- batch_id=4
(3, 13,10000,'2026-03-12','2027-03-12','DONE',       'PRODUCTION', now()),  -- batch_id=5
(3, 14, 3000,'2026-03-12','2027-03-12','DONE',       'PRODUCTION', now()),  -- batch_id=6
(4, 15, 5000,'2026-03-16','2027-03-16','DONE',       'PRODUCTION', now()),  -- batch_id=7
(5,  9, 8000,'2026-03-20','2027-03-20','PROCESSING', 'PRODUCTION', now()),  -- batch_id=8
(5, 10, 8000,'2026-03-20','2027-03-20','PROCESSING', 'PRODUCTION', now()),  -- batch_id=9
-- [NEW MOCK DATA] Các lô nhập và sản xuất số lượng lớn (>1000)
(NULL, 16, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 10 (Mua Đùi gà)
(NULL, 17, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 11 (Mua Coca)
(6,    18, 1500, '2026-03-22', '2026-08-19', 'DONE', 'PRODUCTION', now()), -- batch_id = 12 (Sản xuất Sốt Tỏi)
(6,    19, 1500, '2026-03-22', '2026-08-19', 'DONE', 'PRODUCTION', now()), -- batch_id = 13 (Sản xuất Cơm Gà)
(6,    20, 1500, '2026-03-22', '2026-08-19', 'DONE', 'PRODUCTION', now()), -- batch_id = 14 (Sản xuất Khoai Tây)
(6,    21, 1500, '2026-03-22', '2026-08-19', 'DONE', 'PRODUCTION', now()), -- batch_id = 15 (Sản xuất Pudding)
-- [EXTENDED MOCK DATA] Tạo lô PURCHASE cho 8 Raw Materials cũ chống rỗng kho
(NULL, 1, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 16 (Flour)
(NULL, 2, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 17 (Sugar)
(NULL, 3, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 18 (Milk)
(NULL, 4, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 19 (Butter)
(NULL, 5, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 20 (Chocolate)
(NULL, 6, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 21 (Cake Base)
(NULL, 7, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 22 (Cream Mix)
(NULL, 8, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 23 (Chocolate Filling)
-- [EXTENDED MOCK DATA] Tạo lô PURCHASE cho Raw Materials mới
(NULL, 22, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 24 (Beef)
(NULL, 23, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 25 (Pasta)
(NULL, 24, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 26 (Tomato Sauce)
(NULL, 25, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 27 (Pizza Dough)
(NULL, 26, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 28 (Cheese)
(NULL, 27, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 29 (Potato)
(NULL, 28, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 30 (Bread)
(NULL, 29, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 31 (Coffee Bean)
(NULL, 30, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 32 (Chicken Wings)
-- [EXTENDED MOCK DATA] Tạo lô PURCHASE cho Beverage mới (Pepsi, Orange Juice)
(NULL, 38, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 33 (Pepsi)
(NULL, 39, 2000, '2026-03-20', '2026-08-17', 'DONE', 'PURCHASE',   now()), -- batch_id = 34 (Orange Juice)
-- [EXTENDED MOCK DATA] Tạo lô PRODUCTION 8 cho 4 Món mới
(7,    31, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 35 (Beef Steak)
(7,    32, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 36 (Spaghetti)
(7,    33, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 37 (Margherita Pizza)
(7,    34, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 38 (Chicken Burger)
(7,    35, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 39 (French Fries)
(7,    36, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 40 (Garlic Bread)
(7,    37, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()), -- batch_id = 41 (Fried Chicken Wings)
(7,    40, 1500, '2026-03-23', '2026-08-20', 'DONE', 'PRODUCTION', now()); -- batch_id = 42 (Iced Latte)

-- =============================
-- INVENTORIES
-- =============================
INSERT INTO inventories(product_id,batch_id,quantity,expiry_date) VALUES
(9,  1, 4990, '2027-03-02'),  -- [FIX] 5000 (DRAFT, chưa trừ kho)
(10, 2, 4995, '2027-03-02'),  -- [FIX] 5000 (DRAFT, chưa trừ kho)
(11, 3, 3994, '2027-03-07'),  -- [FIX] 4000 (DRAFT, chưa trừ kho)
(12, 4, 5990, '2027-03-07'),  -- OK: 6000 - 10 = 5990
(13, 5, 9980, '2027-03-12'),  -- OK: 10000 - 20 = 9980
(14, 6, 2995, '2027-03-12'),  -- OK: 3000 - 5 = 2995
(15, 7, 4992, '2027-03-16'),  -- OK: 5000 - 8 = 4992
-- [NEW MOCK DATA] Đẩy lô hàng khủng vào Tồn Kho Thực Tế (>1000)
(16, 10, 2000, '2026-08-17'), -- Tồn đùi gà
(17, 11, 2000, '2026-08-17'), -- Tồn Coca
(18, 12, 1500, '2026-08-19'), -- Tồn Sốt tỏi
(19, 13, 1500, '2026-08-19'), -- Tồn Cơm gà
(20, 14, 1500, '2026-08-19'), -- Tồn Khoai tây nghiền
(21, 15, 1500, '2026-08-19'), -- Tồn Pudding xoài
-- [EXTENDED MOCK DATA] Tồn kho cho 8 Raw Materials cũ chống rỗng kho
(1, 16, 2000, '2026-08-17'),
(2, 17, 2000, '2026-08-17'),
(3, 18, 2000, '2026-08-17'),
(4, 19, 2000, '2026-08-17'),
(5, 20, 2000, '2026-08-17'),
(6, 21, 2000, '2026-08-17'),
(7, 22, 2000, '2026-08-17'),
(8, 23, 2000, '2026-08-17'),
-- [EXTENDED MOCK DATA] Tồn kho cho Raw Materials mới
(22, 24, 2000, '2026-08-17'),
(23, 25, 2000, '2026-08-17'),
(24, 26, 2000, '2026-08-17'),
(25, 27, 2000, '2026-08-17'),
(26, 28, 2000, '2026-08-17'),
(27, 29, 2000, '2026-08-17'),
(28, 30, 2000, '2026-08-17'),
(29, 31, 2000, '2026-08-17'),
(30, 32, 2000, '2026-08-17'),
-- [EXTENDED MOCK DATA] Tồn kho cho Beverage mới
(38, 33, 2000, '2026-08-17'),
(39, 34, 2000, '2026-08-17'),
-- [EXTENDED MOCK DATA] Tồn kho cho 8 Món mới (Thành phẩm nấu)
(31, 35, 1500, '2026-08-20'),
(32, 36, 1500, '2026-08-20'),
(33, 37, 1500, '2026-08-20'),
(34, 38, 1500, '2026-08-20'),
(35, 39, 1500, '2026-08-20'),
(36, 40, 1500, '2026-08-20'),
(37, 41, 1500, '2026-08-20'),
(40, 42, 1500, '2026-08-20');

-- =============================
-- DELIVERIES
-- =============================
INSERT INTO deliveries(delivery_date,shipper_id,created_at, status) VALUES
('2026-03-05', 12, now(), 'DONE'),  -- delivery_id=1, Shipper A giao ngày 05/03
('2026-03-06', 13, now(), 'DONE'),  -- delivery_id=2, Shipper B giao ngày 06/03
('2026-03-07', 14, now(), 'DONE'),  -- delivery_id=3, Shipper C giao ngày 07/03
('2026-03-08', 15, now(), 'DONE');  -- delivery_id=4, Shipper D giao ngày 08/03

-- =============================
-- ORDERS
-- =============================
INSERT INTO orders(parent_order_id,delivery_id,store_id,order_date,type,status,img,comment) VALUES
(NULL, NULL, 1, '2026-03-05 08:00:00', 'NORMAL', 'WAITING',    NULL, ''),
(NULL, NULL, 2, '2026-03-05 09:00:00', 'NORMAL', 'WAITING',    NULL, ''),
(NULL, 2,    3, '2026-03-06 08:00:00', 'NORMAL', 'DISPATCHED', NULL, ''),
(NULL, 3,    4, '2026-03-07 08:00:00', 'NORMAL', 'DELIVERING', NULL, ''),
(NULL, 1,    5, '2026-03-05 10:00:00', 'NORMAL', 'DONE',       NULL, ''),
(NULL, 1,    1, '2026-03-05 11:00:00', 'NORMAL', 'DONE',       NULL, ''),
(NULL, NULL, 2, '2026-03-08 08:00:00', 'NORMAL', 'WAITING',    NULL, ''),
(NULL, NULL, 3, '2026-03-08 09:00:00', 'NORMAL', 'WAITING',    NULL, '');

-- =============================
-- ORDER DETAILS
-- =============================
INSERT INTO order_details(order_id,product_id,quantity) VALUES
(1, 9,  10),  -- order_detail_id=1: order 1 cần 10 Strawberry Cake
(1, 10,  5),  -- order_detail_id=2: order 1 cần 5  Chocolate Cake
(2, 11,  6),  -- order_detail_id=3: order 2 cần 6  Tiramisu
(3, 12, 10),  -- order_detail_id=4: order 3 cần 10 Matcha Cake
(4, 13, 20),  -- order_detail_id=5: order 4 cần 20 Cupcake
(5, 14,  5),  -- order_detail_id=6: order 5 cần 5  Cheesecake
(6, 15,  8),  -- order_detail_id=7: order 6 cần 8  Croissant
(7, 9,  12),  -- order_detail_id=8: order 7 cần 12 Strawberry Cake
(8, 10, 10);  -- order_detail_id=9: order 8 cần 10 Chocolate Cake

-- =============================
-- RECEIPTS
-- =============================
INSERT INTO receipts(receipt_code,order_id,status,note) VALUES
('PXK-001', 1, 'READY',     'Phiếu xuất cho order 1 — đang soạn vì order còn WAITING'),   -- receipt_id=1
('PXK-002', 2, 'READY',     'Phiếu xuất cho order 2 — đang soạn vì order còn PROCESSING'), -- receipt_id=2
('PXK-003', 3, 'COMPLETED', 'Phiếu xuất cho order 3 — đã xuất kho, order DISPATCHED'),      -- receipt_id=3
('PXK-004', 4, 'COMPLETED', 'Phiếu xuất cho order 4 — đã xuất kho, order DELIVERING'),      -- receipt_id=4 [SỬA: DRAFT→COMPLETED]
('PXK-005', 5, 'COMPLETED', 'Phiếu xuất cho order 5 — đã xuất kho, order DONE'),            -- receipt_id=5
('PXK-006', 6, 'COMPLETED', 'Phiếu xuất cho order 6 — đã xuất kho, order DONE'),            -- receipt_id=6 [SỬA: thêm mới]
('PXK-007', 7, 'READY',     'Phiếu xuất cho order 7 — đang soạn vì order còn PROCESSING'), -- receipt_id=7 [SỬA: thêm mới]
('PXK-008', 8, 'READY',     'Phiếu xuất cho order 8 — đang soạn vì order còn WAITING');   -- receipt_id=8 [SỬA: thêm mới]

-- =============================
-- INVENTORY TRANSACTIONS
-- =============================
INSERT INTO inventory_transactions(product_id,batch_id,type,quantity,created_at,note,receipt_id) VALUES
-- PXK-003: order 3 (DISPATCHED) — xuất Matcha Cake lô 4
(12, 4, 'EXPORT', 10, now(), 'Xuất kho cho order 3 - Matcha Cake',      3),  -- transaction_id=1

-- PXK-004: order 4 (DELIVERING) — xuất Cupcake lô 5 [SỬA: thêm mới]
(13, 5, 'EXPORT', 20, now(), 'Xuất kho cho order 4 - Cupcake',          4),  -- transaction_id=2

-- PXK-005: order 5 (DONE) — xuất Cheesecake lô 6
(14, 6, 'EXPORT',  5, now(), 'Xuất kho cho order 5 - Cheesecake',       5),  -- transaction_id=3

-- PXK-006: order 6 (DONE) — xuất Croissant lô 7 [SỬA: thêm mới]
(15, 7, 'EXPORT',  8, now(), 'Xuất kho cho order 6 - Croissant',        6),  -- transaction_id=4

-- [NEW MOCK DATA] Lịch sử Nhập xuất kho (>1000 quy trình chuẩn)
(16, 10, 'IMPORT', 2000, now(), 'Nhập kho lô mua Đùi gà (Raw Material)',  NULL),
(17, 11, 'IMPORT', 2000, now(), 'Nhập kho lô mua Coca Cola (Beverage)',   NULL),
(18, 12, 'IMPORT', 1500, now(), 'Nhập kho lô Sốt tỏi vừa nấu (Sauce)',    NULL),
(19, 13, 'IMPORT', 1500, now(), 'Nhập kho lô Cơm gà nướng vừa nấu (Main)', NULL),
(20, 14, 'IMPORT', 1500, now(), 'Nhập kho lô Khoai tây nghiền (Side)',    NULL),
(21, 15, 'IMPORT', 1500, now(), 'Nhập kho lô Pudding xoài (Dessert)',     NULL),
(2,  NULL, 'EXPORT', 300,  now(), 'Hệ thống tự động xuất Đường (Sugar) nấu Tỏi và Pudding',       NULL),
(16, 10,   'EXPORT', 750,  now(), 'Hệ thống tự động xuất Đùi gà tử lô 10 nấu Cơm Gà Nướng',       NULL), 
(18, 12,   'EXPORT', 75,   now(), 'Hệ thống tự động xuất Sốt Tỏi từ lô 12 chế biến Cơm Gà',       NULL),
(4,  NULL, 'EXPORT', 300,  now(), 'Hệ thống tự động xuất Bơ (Butter) nấu Mash Potato',            NULL),
(3,  NULL, 'EXPORT', 450,  now(), 'Hệ thống tự động xuất Sữa (Milk) nấu Potato & Pudding',        NULL),
-- [EXTENDED MOCK DATA] Ghi nhận IMPORT cho Raw Material cũ
(1, 16, 'IMPORT', 2000, now(), 'Nhập kho lô Flour', NULL),
(2, 17, 'IMPORT', 2000, now(), 'Nhập kho lô Sugar', NULL),
(3, 18, 'IMPORT', 2000, now(), 'Nhập kho lô Milk', NULL),
(4, 19, 'IMPORT', 2000, now(), 'Nhập kho lô Butter', NULL),
(5, 20, 'IMPORT', 2000, now(), 'Nhập kho lô Chocolate', NULL),
(6, 21, 'IMPORT', 2000, now(), 'Nhập kho lô Cake Base', NULL),
(7, 22, 'IMPORT', 2000, now(), 'Nhập kho lô Cream Mix', NULL),
(8, 23, 'IMPORT', 2000, now(), 'Nhập kho lô Choco Filling', NULL),
-- [EXTENDED MOCK DATA] IMPORT cho Raw Materials mới & Beverage
(22, 24, 'IMPORT', 2000, now(), 'Nhập kho lô Beef', NULL),
(23, 25, 'IMPORT', 2000, now(), 'Nhập kho lô Pasta', NULL),
(24, 26, 'IMPORT', 2000, now(), 'Nhập kho lô Tomato Sauce', NULL),
(25, 27, 'IMPORT', 2000, now(), 'Nhập kho lô Pizza Dough', NULL),
(26, 28, 'IMPORT', 2000, now(), 'Nhập kho lô Cheese', NULL),
(27, 29, 'IMPORT', 2000, now(), 'Nhập kho lô Potato', NULL),
(28, 30, 'IMPORT', 2000, now(), 'Nhập kho lô Bread', NULL),
(29, 31, 'IMPORT', 2000, now(), 'Nhập kho lô Coffee Bean', NULL),
(30, 32, 'IMPORT', 2000, now(), 'Nhập kho lô Chicken Wings', NULL),
(38, 33, 'IMPORT', 2000, now(), 'Nhập kho lô Pepsi', NULL),
(39, 34, 'IMPORT', 2000, now(), 'Nhập kho lô Orange Juice', NULL),
-- [EXTENDED MOCK DATA] IMPORT cho Thành phẩm
(31, 35, 'IMPORT', 1500, now(), 'Nhập kho Beef Steak', NULL),
(32, 36, 'IMPORT', 1500, now(), 'Nhập kho Spaghetti', NULL),
(33, 37, 'IMPORT', 1500, now(), 'Nhập kho Pizza', NULL),
(34, 38, 'IMPORT', 1500, now(), 'Nhập kho Chicken Burger', NULL),
(35, 39, 'IMPORT', 1500, now(), 'Nhập kho French Fries', NULL),
(36, 40, 'IMPORT', 1500, now(), 'Nhập kho Garlic Bread', NULL),
(37, 41, 'IMPORT', 1500, now(), 'Nhập kho Fried Chicken Wings', NULL),
(40, 42, 'IMPORT', 1500, now(), 'Nhập kho Iced Latte', NULL),
-- [EXTENDED MOCK DATA] EXPORT trừ nguyên liệu 
(22, 24, 'EXPORT', 10500, now(), 'Xuất thịt bò', NULL),
(4,  19, 'EXPORT', 1500,  now(), 'Xuất bơ', NULL),
(23, 25, 'EXPORT', 3000,  now(), 'Xuất Mì Ý', NULL),
(24, 26, 'EXPORT', 3000,  now(), 'Xuất Tomato Sauce', NULL),
(25, 27, 'EXPORT', 15000, now(), 'Xuất Pizza Dough', NULL),
(26, 28, 'EXPORT', 4500,  now(), 'Xuất Cheese', NULL),
(28, 30, 'EXPORT', 30000, now(), 'Xuất Bánh mì', NULL),
(16, 10, 'EXPORT', 4500,  now(), 'Xuất Đùi Gà', NULL),
(27, 29, 'EXPORT', 7500,  now(), 'Xuất Khoai tây', NULL),
(18, 12, 'EXPORT', 750,   now(), 'Xuất Garlic Sauce', NULL),
(30, 32, 'EXPORT', 7500,  now(), 'Xuất Cánh Gà chiên', NULL),
(1,  16, 'EXPORT', 1500,  now(), 'Xuất Bột mì rán gà', NULL),
(29, 31, 'EXPORT', 750,   now(), 'Xuất Hạt cà phê', NULL),
(3,  18, 'EXPORT', 3000,  now(), 'Xuất Sữa pha Latte', NULL); 

-- Lưu ý: order 1 & 2 chưa có EXPORT transaction vì receipt còn DRAFT
-- Lưu ý: order 7 & 8 chưa có EXPORT transaction vì receipt còn DRAFT

-- =============================
-- ORDER DETAIL FILL
-- =============================
INSERT INTO order_detail_fill(order_detail_id,batch_id,quantity,created_at) VALUES
(1, 1, 10, now()),  -- [FIX] fill order_detail 1 (order 1, Strawberry qty=10) từ lô 1
(2, 2,  5, now()),  -- [FIX] fill order_detail 2 (order 1, Chocolate qty=5)  từ lô 2
-- order 2 (PROCESSING): order_detail_id=3, cần 6 Tiramisu → lấy từ lô 3
(3, 3, 6,  now()),  -- fill order_detail 3 (order 2, Tiramisu qty=6) từ lô 3 ← [SỬA: thêm mới theo flow]

-- order 3 (DISPATCHED): order_detail_id=4, cần 10 Matcha Cake → lấy từ lô 4
(4, 4, 10, now()),  -- fill order_detail 4 (order 3, Matcha Cake qty=10) từ lô 4

-- order 4 (DELIVERING): order_detail_id=5, cần 20 Cupcake → lấy từ lô 5
(5, 5, 20, now()),  -- fill order_detail 5 (order 4, Cupcake qty=20) từ lô 5

-- order 5 (DONE): order_detail_id=6, cần 5 Cheesecake → lấy từ lô 6
(6, 6, 5,  now()),  -- fill order_detail 6 (order 5, Cheesecake qty=5) từ lô 6

-- order 6 (DONE): order_detail_id=7, cần 8 Croissant → lấy từ lô 7
(7, 7, 8,  now());  -- fill order_detail 7 (order 6, Croissant qty=8) từ lô 7

-- order 7 (PROCESSING): order_detail_id=8, cần 12 Strawberry Cake
-- FEFO: lô 1 (expiry 03-05) hết hạn rồi → dùng lô 8 (expiry 03-23, đang PROCESSING)
-- Nhưng lô 8 status=PROCESSING (chưa sản xuất xong) → CHƯA CÓ trong inventories
-- → Thực tế không thể fill từ lô chưa nhập kho
-- → Tạm fill NULL hoặc để hệ thống chờ, ở đây insert với batch khả dụng gần nhất
-- Lô 1 expiry 2026-03-05 < ngày hiện tại 2026-03-09 → ĐÃ HẾT HẠN, không dùng được
-- → order 7 bị tình trạng: KHÔNG ĐỦ HÀNG để fill ← cần chú ý nghiệp vụ

-- =============================
-- QUALITY FEEDBACKS
-- =============================
INSERT INTO quality_feedbacks(order_id,rating,comment,created_at) VALUES
(5, 5, 'Great quality, very fresh!', now()),  -- feedback cho order 5 (DONE)
(6, 4, 'Good cake, will order again', now()); -- feedback cho order 6 (DONE)
-- [SỬA] Xóa feedback của order 3 (status=DISPATCHED, chưa giao xong, không thể feedback)

-- ============================================
-- WASTE LOGS
-- ============================================
INSERT INTO waste_logs(product_id, batch_id, quantity, waste_type, order_id, note, created_at) VALUES
(12, 4, 2, 'EXPIRED',          NULL, 'Matcha Cake hết hạn trong kho, hủy lô 4',          now()), -- Hàng hết hạn
(13, 5, 3, 'DAMAGED_SHIPPING', 4,    'Cupcake bị hỏng khi giao order 4, lô 5',           now()), -- Hàng hỏng khi giao
(15, 7, 1, 'DAMAGED_SHIPPING', 6,    'Croissant bị bể khi giao order 6, lô 7',           now()), -- Hàng hỏng khi giao
(14, 6, 1, 'EXPIRED',          NULL, 'Cheesecake phát hiện hỏng khi kiểm tra lô 6',      now()); -- Hàng hết hạn

COMMIT;

/*==============================================================================================================================================================*/
/*==============================================================================================================================================================*/
/*==================================================================ADDING MOCK DATA============================================================================*/
/*==============================================================================================================================================================*/
/*==============================================================================================================================================================*/
