-- select * from orders

-- select * from products

-- select * from stores

-- select * from order_details

-- select * from order_detail_fill

-- select * from deliveries

-- select * from users

-- select * from receipts

/*=========================================================================================================*/
--CODE FOR RESET DATABASE POSTGRESQL
-- 1. Xóa sổ toàn bộ Schema public (bao gồm mọi Table, View, Type,...)
BEGIN;

DROP SCHEMA public CASCADE;

-- 2. Tạo lại Schema public mới trắng tinh
CREATE SCHEMA public;

-- 3. Cấp lại quyền truy cập cho user của bạn (User trong ảnh bạn gửi)
GRANT ALL ON SCHEMA public TO public;
-- GRANT ALL ON SCHEMA public TO central_kitchen_user;
GRANT ALL ON SCHEMA public TO kitchencontroldb_user;

COMMIT;
/*=========================================================================================================*/


CREATE TYPE "product_type_enum" AS ENUM (
    'RAW_MATERIAL',
    'SEMI_FINISHED',
    'MAIN',
	'SIDE',
	'BEVERAGE',
	'DESSERT',
	'SAUCE'
    );

CREATE TYPE "orders_status" AS ENUM (
    'WAITING',
    'PROCESSING',
	'DISPATCHED',
    'DELIVERING',
	'PARTIAL_DELIVERED',
    'DONE',
    'DAMAGED',
    'CANCELED'
    );

CREATE TYPE "log_batches_enum" AS ENUM (
    'PROCESSING',
	'WAITING_TO_CONFIRM',
    'DONE',
	'WAITING_TO_CANCEL',
    'DAMAGED'
    );

CREATE TYPE "log_batches_type" AS ENUM (
    'PRODUCTION',
    'PURCHASE'
    );

CREATE TYPE "inventories_type" AS ENUM (
    'IMPORT',
    'EXPORT'
    );

CREATE TYPE "receipt_status" AS ENUM (
  'DRAFT',
  'COMPLETED',
  'CANCELED'
);

CREATE TYPE "deliveries_status" AS ENUM (
	'DRAFT',
    'WAITING',
    'DELIVERING',
	'DONE',
	'CANCEL'
    );

CREATE TYPE "production_plan_status" AS ENUM (
    'PROCESSING',
	'COMPLETE_ONE_SECTION',
	'DONE'
    );

CREATE TABLE "roles" (
                         "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "role_name" varchar
);

CREATE TABLE "users" (
                         "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar,
                         "password" varchar,
                         "full_name" varchar,
                         "role_id" int,
                         "store_id" int
);

CREATE TABLE "stores" (
                          "store_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "store_name" varchar,
                          "address" varchar,
                          "phone" varchar
);

CREATE TABLE "products" (
                            "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "product_name" varchar,
                            "product_type" product_type_enum,
                            "unit" varchar,
							"price" float,
                            "shelf_life_days" int
);

CREATE TABLE "recipes" (
                           "recipe_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "product_id" int,
                           "recipe_name" varchar,
                           "yield_quantity" float,
                           "description" text
);

CREATE TABLE "recipe_details" (
                                  "recipe_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "recipe_id" int,
                                  "raw_material_id" int,
                                  "quantity" float
);

CREATE TABLE "production_plans" (
                                    "plan_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "plan_date" date,
                                    "start_date" date,
                                    "end_date" date,
                                    "status" production_plan_status,
                                    "note" text
);

CREATE TABLE "production_plan_details" (
                                           "plan_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "plan_id" int NOT NULL,
                                           "product_id" int NOT NULL,
                                           "quantity" float NOT NULL,
                                           "note" text
);

CREATE TABLE "orders" (
                          "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						  "parent_order_id" int
                          "delivery_id" int,
                          "store_id" int,
                          "order_date" timestamp,
						  "type" varchar,
                          "status" orders_status,
                          "img" varchar,
                          "comment" varchar
);

CREATE TABLE "order_details" (
                                 "order_detail_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "order_id" int,
                                 "product_id" int,
                                 "quantity" float
);

CREATE TABLE "log_batches" (
                               "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "plan_id" int,
                               "product_id" int,
                               "quantity" float,
                               "production_date" date,
                               "expiry_date" date,
                               "status" log_batches_enum,
                               "type" log_batches_type,
                               "created_at" timestamp
);

CREATE TABLE "inventories" (
                               "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "product_id" int,
                               "batch_id" int,
                               "quantity" float,
                               "expiry_date" date
);

CREATE TABLE "inventory_transactions" (
                                          "transaction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "product_id" int,
                                          "batch_id" int,
                                          "type" inventories_type,
                                          "quantity" float,
                                          "created_at" timestamp,
                                          "note" text,
                                          "receipt_id" int
);

CREATE TABLE "deliveries" (
                              "delivery_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "delivery_date" date,
                              "shipper_id" int,
							  "status" deliveries_status,
                              "created_at" timestamp
);

CREATE TABLE "quality_feedbacks" (
                                     "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_id" int unique,
                                     "rating" int,
                                     "comment" text,
                                     "created_at" timestamp
);

CREATE TABLE "reports" (
                           "report_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "report_type" varchar,
                           "user_id" int,
                           "created_date" timestamp
);

CREATE TABLE "receipts" (
                            "receipt_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "receipt_code" varchar,
                            "order_id" int,
                            "export_date" timestamp DEFAULT (now()),
                            "status" receipt_status,
                            "note" text
);

CREATE TABLE "order_detail_fill" (
                                     "fill_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "order_detail_id" int NOT NULL,
                                     "batch_id" int NOT NULL,
                                     "quantity" float NOT NULL,
                                     "created_at" timestamp
);

COMMENT ON COLUMN "roles"."role_name" IS 'ADMIN, MANAGER, STORE, SUPPLY_COORDINATOR, WAREHOUSE_KEEPER, SHIPPER';

COMMENT ON COLUMN "users"."store_id" IS 'Unique';

COMMENT ON COLUMN "products"."shelf_life_days" IS 'sản phẩm có thời gian sủ dụng bao ngày (ex: 30 days)';

COMMENT ON COLUMN "recipes"."yield_quantity" IS 'How much this recipe makes';

COMMENT ON COLUMN "log_batches"."production_date" IS 'có thể là ngày sản xuất hoặc ngày nhập hàng';

COMMENT ON COLUMN "inventory_transactions"."receipt_id" IS 'Dòng biến động này thuộc phiếu xuất nào?';

COMMENT ON COLUMN "receipts"."receipt_code" IS 'Mã phiếu, VD: PXK-001';

COMMENT ON COLUMN "receipts"."status" IS 'DRAFT (Đang soạn), COMPLETED (Đã trừ kho), CANCELLED';

ALTER TABLE "receipts" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("receipt_id") REFERENCES "receipts" ("receipt_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("order_detail_id") REFERENCES "order_details" ("order_detail_id");

ALTER TABLE "order_detail_fill" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "users" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "recipes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("recipe_id");

ALTER TABLE "recipe_details" ADD FOREIGN KEY ("raw_material_id") REFERENCES "products" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "order_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "log_batches" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");

-- ALTER TABLE "products" ADD FOREIGN KEY ("product_id") REFERENCES "log_batches" ("product_id");
ALTER TABLE "log_batches" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventories" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

-- ALTER TABLE "log_batches" ADD FOREIGN KEY ("batch_id") REFERENCES "inventories" ("batch_id");
ALTER TABLE "inventories" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "inventory_transactions" ADD FOREIGN KEY ("batch_id") REFERENCES "log_batches" ("batch_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("delivery_id") REFERENCES "deliveries" ("delivery_id");

-- ALTER TABLE "orders" ADD FOREIGN KEY ("order_id") REFERENCES "quality_feedbacks" ("order_id");
ALTER TABLE "quality_feedbacks" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");

ALTER TABLE "reports" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "deliveries" ADD FOREIGN KEY ("shipper_id") REFERENCES "users" ("user_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");

ALTER TABLE "production_plan_details" ADD FOREIGN KEY ("plan_id") REFERENCES "production_plans" ("plan_id");


/*=========================================================================================================*/
/*=========================================================================================================*/
/*=============================================ADDING MOCK DATA============================================*/
/*=========================================================================================================*/
/*=========================================================================================================*/
BEGIN;

-- ============================================
-- ROLES
-- ============================================
INSERT INTO roles (role_name) VALUES 
('ADMIN'),                    -- 1: Quản trị hệ thống
('MANAGER'),                  -- 2: Quản lý
('STORE'),                    -- 3: Nhân viên cửa hàng
('SUPPLY_COORDINATOR'),       -- 4: Điều phối cung ứng
('WAREHOUSE_KEEPER'),         -- 5: Thủ kho
('SHIPPER'),                  -- 6: Nhân viên giao hàng
('KITCHEN_STAFF');            -- 7: Nhân viên bếp

-- =============================
-- STORES
-- =============================
INSERT INTO stores(store_name,address,phone) VALUES
('Store District 1', '12 Nguyen Hue',       '090000001'),  -- store_id = 1
('Store District 2', '22 Tran Nao',         '090000002'),  -- store_id = 2
('Store District 3', '45 Vo Van Tan',       '090000003'),  -- store_id = 3
('Store District 5', '19 Tran Hung Dao',    '090000004'),  -- store_id = 4
('Store District 7', '88 Nguyen Thi Thap',  '090000005');  -- store_id = 5

-- =============================
-- USERS
-- =============================
INSERT INTO users(username,password,full_name,role_id,store_id) VALUES
('admin',      '1', 'System Admin',          1, NULL),  -- user_id=1,  ADMIN, không gắn store
('manager',   '1', 'Manager Nguyen',         2, NULL),  -- user_id=2,  MANAGER
('store1',     '1', 'Store Staff 1',          3, 1),     -- user_id=3,  STORE → store_id=1
('store2',     '1', 'Store Staff 2',          3, 2),     -- user_id=4,  STORE → store_id=2
('store3',     '1', 'Store Staff 3',          3, 3),     -- user_id=5,  STORE → store_id=3
('store4',     '1', 'Store Staff 5',          3, 4),     -- user_id=6,  STORE → store_id=4
('store5',     '1', 'Store Staff 7',          3, 5),     -- user_id=7,  STORE → store_id=5
('supply',    '1', 'Supply Coordinator A',   4, NULL),  -- user_id=8,  SUPPLY_COORDINATOR
('warehouse', '1', 'Warehouse Keeper A',     5, NULL),  -- user_id=9, WAREHOUSE_KEEPER
('kitchen',   '1', 'Kitchen Manager A',     7, NULL),  -- user_id=10, KITCHEN_MANAGER
('shipper1',   '1', 'Shipper A',              6, NULL),  -- user_id=11, SHIPPER
('shipper2',   '1', 'Shipper B',              6, NULL),  -- user_id=12, SHIPPER
('shipper3',   '1', 'Shipper C',              6, NULL),  -- user_id=13, SHIPPER
('shipper4',   '1', 'Shipper D',              6, NULL),  -- user_id=14, SHIPPER
('shipper5',   '1', 'Shipper D',              6, NULL);  -- user_id=15, SHIPPER

-- =============================
-- PRODUCTS
-- =============================
INSERT INTO products(product_name,product_type,unit,shelf_life_days) VALUES
-- RAW MATERIALS (nguyên liệu thô)
('Flour',             'RAW_MATERIAL',     'kg',     365),  -- product_id=1  [SỬA: 180→365]
('Sugar',             'RAW_MATERIAL',     'kg',     365),  -- product_id=2  (giữ nguyên)
('Milk',              'RAW_MATERIAL',     'liter',  365),  -- product_id=3  [SỬA: 30→365]
('Butter',            'RAW_MATERIAL',     'kg',     365),  -- product_id=4  [SỬA: 90→365]
('Chocolate',         'RAW_MATERIAL',     'kg',     365),  -- product_id=5  [SỬA: 120→365]

-- SEMI-FINISHED (bán thành phẩm)
('Cake Base',         'SEMI_FINISHED',    'piece',  365),  -- product_id=6  [SỬA: 5→365]
('Cream Mix',         'SEMI_FINISHED',    'kg',     365),  -- product_id=7  [SỬA: 3→365]
('Chocolate Filling', 'SEMI_FINISHED',    'kg',     365),  -- product_id=8  [SỬA: 7→365]

-- FINISHED PRODUCTS (thành phẩm)
('Strawberry Cake',   'FINISHED_PRODUCT', 'piece',  365),  -- product_id=9  [SỬA: 3→365]
('Chocolate Cake',    'FINISHED_PRODUCT', 'piece',  365),  -- product_id=10 [SỬA: 3→365]
('Tiramisu',          'FINISHED_PRODUCT', 'piece',  365),  -- product_id=11 [SỬA: 2→365]
('Matcha Cake',       'FINISHED_PRODUCT', 'piece',  365),  -- product_id=12 [SỬA: 3→365]
('Cupcake',           'FINISHED_PRODUCT', 'piece',  365),  -- product_id=13 [SỬA: 4→365]
('Cheesecake',        'FINISHED_PRODUCT', 'piece',  365),  -- product_id=14 [SỬA: 3→365]
('Croissant',         'FINISHED_PRODUCT', 'piece',  365);  -- product_id=15 [SỬA: 2→365]

-- =============================
-- RECIPES
-- =============================
INSERT INTO recipes(product_id,recipe_name,yield_quantity,description) VALUES
(6,  'Cake Base Recipe',         20, 'Base dough for layered cakes'),           -- recipe_id=1
(7,  'Cream Mix Recipe',         10, 'Whipped cream mixture'),                  -- recipe_id=2
(8,  'Chocolate Filling Recipe', 10, 'Chocolate ganache filling'),              -- recipe_id=3
(9,  'Strawberry Cake Recipe',   10, 'Strawberry cake using Cake Base & Cream'),-- recipe_id=4
(10, 'Chocolate Cake Recipe',    10, 'Chocolate cake with chocolate filling'),  -- recipe_id=5
(11, 'Tiramisu Recipe',           8, 'Italian dessert with cream mix'),         -- recipe_id=6
(12, 'Matcha Cake Recipe',       10, 'Matcha cake using Cake Base & Cream'),    -- recipe_id=7
(13, 'Cupcake Recipe',           20, 'Small cupcake with cream topping'),       -- recipe_id=8
(14, 'Cheesecake Recipe',        10, 'Classic cheesecake'),                     -- recipe_id=9
(15, 'Croissant Recipe',         20, 'Buttery croissant');                      -- recipe_id=10

-- =============================
-- RECIPE DETAILS
-- =============================
INSERT INTO recipe_details(recipe_id,raw_material_id,quantity) VALUES
(1, 1, 5.0),   -- Cake Base dùng Flour: 5 kg
(1, 2, 2.0),   -- Cake Base dùng Sugar: 2 kg
(1, 4, 1.0),   -- Cake Base dùng Butter: 1 kg

-- Recipe 2: Cream Mix (product_id=7) — dùng RAW MATERIAL
(2, 3, 3.0),   -- Cream Mix dùng Milk: 3 liter
(2, 2, 1.0),   -- Cream Mix dùng Sugar: 1 kg

-- Recipe 3: Chocolate Filling (product_id=8) — dùng RAW MATERIAL
(3, 5, 3.0),   -- Chocolate Filling dùng Chocolate: 3 kg
(3, 3, 1.0),   -- Chocolate Filling dùng Milk: 1 liter

-- Recipe 4: Strawberry Cake (product_id=9) — dùng SEMI_FINISHED
(4, 6, 2.0),   -- Strawberry Cake dùng Cake Base: 2 piece
(4, 7, 1.0),   -- Strawberry Cake dùng Cream Mix: 1 kg

-- Recipe 5: Chocolate Cake (product_id=10) — dùng SEMI_FINISHED
(5, 6, 2.0),   -- Chocolate Cake dùng Cake Base: 2 piece
(5, 8, 1.5),   -- Chocolate Cake dùng Chocolate Filling: 1.5 kg

-- Recipe 6: Tiramisu (product_id=11) — dùng SEMI_FINISHED + RAW
(6, 7, 2.0),   -- Tiramisu dùng Cream Mix: 2 kg
(6, 2, 0.5),   -- Tiramisu dùng Sugar: 0.5 kg

-- Recipe 7: Matcha Cake (product_id=12) — dùng SEMI_FINISHED
(7, 6, 2.0),   -- Matcha Cake dùng Cake Base: 2 piece
(7, 7, 1.0),   -- Matcha Cake dùng Cream Mix: 1 kg

-- Recipe 8: Cupcake (product_id=13) — dùng RAW + SEMI_FINISHED
(8, 1, 1.0),   -- Cupcake dùng Flour: 1 kg
(8, 2, 1.0),   -- Cupcake dùng Sugar: 1 kg
(8, 7, 0.5),   -- Cupcake dùng Cream Mix: 0.5 kg

-- Recipe 9: Cheesecake (product_id=14) — dùng RAW MATERIAL
(9, 3, 2.0),   -- Cheesecake dùng Milk: 2 liter
(9, 2, 1.0),   -- Cheesecake dùng Sugar: 1 kg
(9, 4, 0.5),   -- Cheesecake dùng Butter: 0.5 kg

-- Recipe 10: Croissant (product_id=15) — dùng RAW MATERIAL
(10, 1, 3.0),  -- Croissant dùng Flour: 3 kg
(10, 4, 2.0),  -- Croissant dùng Butter: 2 kg
(10, 2, 0.5);  -- Croissant dùng Sugar: 0.5 kg

-- =============================
-- PRODUCTION PLANS
-- =============================
INSERT INTO production_plans(plan_date,start_date,end_date,status,note) VALUES
('2026-03-01', '2026-03-02', '2026-03-05', 'DONE',       'Weekly production batch 1'),  -- plan_id=1
('2026-03-06', '2026-03-07', '2026-03-10', 'DONE',       'Weekly production batch 2'),  -- plan_id=2 [SỬA: PROCESSING→DONE vì các lô đã DONE]
('2026-03-11', '2026-03-12', '2026-03-14', 'DONE',       'Weekly production batch 3'),  -- plan_id=3 [SỬA: tương tự]
('2026-03-15', '2026-03-16', '2026-03-18', 'PROCESSING', 'Next batch'),                 -- plan_id=4
('2026-03-19', '2026-03-20', '2026-03-22', 'PROCESSING', 'Upcoming production');        -- plan_id=5

-- =============================
-- PRODUCTION PLAN DETAILS
-- =============================
INSERT INTO production_plan_details(plan_id,product_id,quantity,note) VALUES
-- OLD DATA =============================================
--(1, 9,  50, 'Strawberry Cake — plan 1'),   -- plan_detail_id=1
--(1, 10, 50, 'Chocolate Cake — plan 1'),    -- plan_detail_id=2
--(2, 11, 40, 'Tiramisu — plan 2'),          -- plan_detail_id=3
--(2, 12, 60, 'Matcha Cake — plan 2'),       -- plan_detail_id=4
--(3, 13,100, 'Cupcake — plan 3'),           -- plan_detail_id=5
--(3, 14, 30, 'Cheesecake — plan 3'),        -- plan_detail_id=6
--(4, 15, 50, 'Croissant — plan 4'),         -- plan_detail_id=7
--(5, 9,  80, 'Strawberry Cake — plan 5'),   -- plan_detail_id=8
--(5, 10, 80, 'Chocolate Cake — plan 5');    -- plan_detail_id=9

-- NEW DATA =============================================
(1,  9, 5000, 'Strawberry Cake — plan 1'),
(1, 10, 5000, 'Chocolate Cake — plan 1'),
(2, 11, 4000, 'Tiramisu — plan 2'),
(2, 12, 6000, 'Matcha Cake — plan 2'),
(3, 13,10000, 'Cupcake — plan 3'),
(3, 14, 3000, 'Cheesecake — plan 3'),
(4, 15, 5000, 'Croissant — plan 4'),
(5,  9, 8000, 'Strawberry Cake — plan 5'),
(5, 10, 8000, 'Chocolate Cake — plan 5');

-- =============================
-- LOG BATCHES
-- =============================
INSERT INTO log_batches(plan_id,product_id,quantity,production_date,expiry_date,status,type,created_at) VALUES
-- OLD DATA =============================================
--(1, 9,  50, '2026-03-02', '2027-03-02', 'DONE',       'PRODUCTION', now()),  -- batch_id=1: Strawberry 2026-03-02 + 365 = 2027-03-02
--(1, 10, 50, '2026-03-02', '2027-03-02', 'DONE',       'PRODUCTION', now()),  -- batch_id=2: Chocolate  2026-03-02 + 365 = 2027-03-02
--(2, 11, 40, '2026-03-07', '2027-03-07', 'DONE',       'PRODUCTION', now()),  -- batch_id=3: Tiramisu   2026-03-07 + 365 = 2027-03-07
--(2, 12, 60, '2026-03-07', '2027-03-07', 'DONE',       'PRODUCTION', now()),  -- batch_id=4: Matcha     2026-03-07 + 365 = 2027-03-07
--(3, 13,100, '2026-03-12', '2027-03-12', 'DONE',       'PRODUCTION', now()),  -- batch_id=5: Cupcake    2026-03-12 + 365 = 2027-03-12
--(3, 14, 30, '2026-03-12', '2027-03-12', 'DONE',       'PRODUCTION', now()),  -- batch_id=6: Cheesecake 2026-03-12 + 365 = 2027-03-12
--(4, 15, 50, '2026-03-16', '2027-03-16', 'DONE',       'PRODUCTION', now()),  -- batch_id=7: Croissant  2026-03-16 + 365 = 2027-03-16
--(5, 9,  80, '2026-03-20', '2027-03-20', 'PROCESSING', 'PRODUCTION', now()),  -- batch_id=8: Strawberry 2026-03-20 + 365 = 2027-03-20 (chưa nhập kho)
--(5, 10, 80, '2026-03-20', '2027-03-20', 'PROCESSING', 'PRODUCTION', now());  -- batch_id=9: Chocolate  2026-03-20 + 365 = 2027-03-20 (chưa nhập kho)

--NEW DATA =============================================
(1,  9, 5000,'2026-03-02','2027-03-02','DONE',       'PRODUCTION', now()),  -- batch_id=1
(1, 10, 5000,'2026-03-02','2027-03-02','DONE',       'PRODUCTION', now()),  -- batch_id=2
(2, 11, 4000,'2026-03-07','2027-03-07','DONE',       'PRODUCTION', now()),  -- batch_id=3
(2, 12, 6000,'2026-03-07','2027-03-07','DONE',       'PRODUCTION', now()),  -- batch_id=4
(3, 13,10000,'2026-03-12','2027-03-12','DONE',       'PRODUCTION', now()),  -- batch_id=5
(3, 14, 3000,'2026-03-12','2027-03-12','DONE',       'PRODUCTION', now()),  -- batch_id=6
(4, 15, 5000,'2026-03-16','2027-03-16','DONE',       'PRODUCTION', now()),  -- batch_id=7
(5,  9, 8000,'2026-03-20','2027-03-20','PROCESSING', 'PRODUCTION', now()),  -- batch_id=8
(5, 10, 8000,'2026-03-20','2027-03-20','PROCESSING', 'PRODUCTION', now());  -- batch_id=9

-- =============================
-- INVENTORIES
-- =============================
INSERT INTO inventories(product_id,batch_id,quantity,expiry_date) VALUES
-- OLD DATA =============================================
--(9,  1, 40, '2027-03-02'),  -- Strawberry Cake  lô 1: 50 sản xuất - 10 xuất (order 1 fill, chưa trừ kho) = 40 còn lại
--(10, 2, 45, '2027-03-02'),  -- Chocolate Cake   lô 2: 50 sản xuất - 5  xuất (order 1 fill, chưa trừ kho) = 45 còn lại
--(11, 3, 34, '2027-03-07'),  -- Tiramisu         lô 3: 40 sản xuất - 6  xuất (order 2 fill) = 34 còn lại
--(12, 4, 50, '2027-03-07'),  -- Matcha Cake      lô 4: 60 sản xuất - 10 xuất (order 3, đã EXPORT transaction) = 50 còn lại
--(13, 5, 80, '2027-03-12'),  -- Cupcake          lô 5: 100 sản xuất - 20 xuất (order 4, đã EXPORT transaction) = 80 còn lại
--(14, 6, 25, '2027-03-12'),  -- Cheesecake       lô 6: 30 sản xuất - 5  xuất (order 5, đã EXPORT transaction) = 25 còn lại
--(15, 7, 42, '2027-03-16');  -- Croissant        lô 7: 50 sản xuất - 8  xuất (order 6, đã EXPORT transaction) = 42 còn lại

-- NEW DATA =============================================
(9,  1, 4990, '2027-03-02'),  -- Strawberry Cake  lô 1: 5000 sản xuất - 10 xuất (order 1 fill, chưa trừ kho) = 4990 còn lại
(10, 2, 4995, '2027-03-02'),  -- Chocolate Cake   lô 2: 5000 sản xuất - 5  xuất (order 1 fill, chưa trừ kho) = 4995 còn lại
(11, 3, 3994, '2027-03-07'),  -- Tiramisu         lô 3: 4000 sản xuất - 6  xuất (order 2 fill) = 3994 còn lại
(12, 4, 5990, '2027-03-07'),  -- Matcha Cake      lô 4: 6000 sản xuất - 10 xuất (order 3, đã EXPORT transaction) = 5990 còn lại
(13, 5, 9980, '2027-03-12'),  -- Cupcake          lô 5: 10000 sản xuất - 20 xuất (order 4, đã EXPORT transaction) = 9980 còn lại
(14, 6, 2995, '2027-03-12'),  -- Cheesecake       lô 6: 3000 sản xuất - 5  xuất (order 5, đã EXPORT transaction) = 2995 còn lại
(15, 7, 4992, '2027-03-16');  -- Croissant        lô 7: 5000 sản xuất - 8  xuất (order 6, đã EXPORT transaction) = 4992 còn lại

-- =============================
-- DELIVERIES
-- =============================
INSERT INTO deliveries(delivery_date,shipper_id,created_at, status) VALUES
('2026-03-05', 12, now(), 'DONE'),  -- delivery_id=1, Shipper A giao ngày 05/03
('2026-03-06', 13, now(), 'DONE'),  -- delivery_id=2, Shipper B giao ngày 06/03
('2026-03-07', 14, now(), 'DONE'),  -- delivery_id=3, Shipper C giao ngày 07/03
('2026-03-08', 15, now(), 'DONE');  -- delivery_id=4, Shipper D giao ngày 08/03

-- =============================
-- ORDERS
-- =============================
INSERT INTO orders(delivery_id,store_id,order_date,status,img,comment) VALUES
(NULL, 1, '2026-03-05 08:00:00', 'WAITING',   NULL, ''),  -- order_id=1: Store 1, chưa xử lý, chưa có delivery
(NULL, 2, '2026-03-05 09:00:00', 'WAITING', NULL, ''),  -- order_id=2: Store 2, đang xử lý, chưa có delivery
(2,    3, '2026-03-06 08:00:00', 'DISPATCHED', NULL, ''),  -- order_id=3: Store 3, đã dispatch → có delivery_id=2
(3,    4, '2026-03-07 08:00:00', 'DELIVERING', NULL, ''),  -- order_id=4: Store 4, đang giao → có delivery_id=3
(1,    5, '2026-03-05 10:00:00', 'DONE',       NULL, ''),  -- order_id=5: Store 5, đã hoàn thành → delivery_id=1
(1,    1, '2026-03-05 11:00:00', 'DONE',       NULL, ''),  -- order_id=6: Store 1, đã hoàn thành → delivery_id=1
(NULL, 2, '2026-03-08 08:00:00', 'WAITING', NULL, ''),  -- order_id=7: Store 2, đang xử lý, chưa có delivery
(NULL, 3, '2026-03-08 09:00:00', 'WAITING',   NULL, '');  -- order_id=8: Store 3, chưa xử lý, chưa có delivery

-- =============================
-- ORDER DETAILS
-- =============================
INSERT INTO order_details(order_id,product_id,quantity) VALUES
(1, 9,  10),  -- order_detail_id=1: order 1 cần 10 Strawberry Cake
(1, 10,  5),  -- order_detail_id=2: order 1 cần 5  Chocolate Cake
(2, 11,  6),  -- order_detail_id=3: order 2 cần 6  Tiramisu
(3, 12, 10),  -- order_detail_id=4: order 3 cần 10 Matcha Cake
(4, 13, 20),  -- order_detail_id=5: order 4 cần 20 Cupcake
(5, 14,  5),  -- order_detail_id=6: order 5 cần 5  Cheesecake
(6, 15,  8),  -- order_detail_id=7: order 6 cần 8  Croissant
(7, 9,  12),  -- order_detail_id=8: order 7 cần 12 Strawberry Cake
(8, 10, 10);  -- order_detail_id=9: order 8 cần 10 Chocolate Cake

-- =============================
-- RECEIPTS
-- =============================
INSERT INTO receipts(receipt_code,order_id,status,note) VALUES
('PXK-001', 1, 'DRAFT',     'Phiếu xuất cho order 1 — đang soạn vì order còn WAITING'),   -- receipt_id=1
('PXK-002', 2, 'DRAFT',     'Phiếu xuất cho order 2 — đang soạn vì order còn PROCESSING'), -- receipt_id=2
('PXK-003', 3, 'COMPLETED', 'Phiếu xuất cho order 3 — đã xuất kho, order DISPATCHED'),      -- receipt_id=3
('PXK-004', 4, 'COMPLETED', 'Phiếu xuất cho order 4 — đã xuất kho, order DELIVERING'),      -- receipt_id=4 [SỬA: DRAFT→COMPLETED]
('PXK-005', 5, 'COMPLETED', 'Phiếu xuất cho order 5 — đã xuất kho, order DONE'),            -- receipt_id=5
('PXK-006', 6, 'COMPLETED', 'Phiếu xuất cho order 6 — đã xuất kho, order DONE'),            -- receipt_id=6 [SỬA: thêm mới]
('PXK-007', 7, 'DRAFT',     'Phiếu xuất cho order 7 — đang soạn vì order còn PROCESSING'), -- receipt_id=7 [SỬA: thêm mới]
('PXK-008', 8, 'DRAFT',     'Phiếu xuất cho order 8 — đang soạn vì order còn WAITING');   -- receipt_id=8 [SỬA: thêm mới]

-- =============================
-- INVENTORY TRANSACTIONS
-- =============================
INSERT INTO inventory_transactions(product_id,batch_id,type,quantity,created_at,note,receipt_id) VALUES
-- PXK-003: order 3 (DISPATCHED) — xuất Matcha Cake lô 4
(12, 4, 'EXPORT', 10, now(), 'Xuất kho cho order 3 - Matcha Cake',      3),  -- transaction_id=1

-- PXK-004: order 4 (DELIVERING) — xuất Cupcake lô 5 [SỬA: thêm mới]
(13, 5, 'EXPORT', 20, now(), 'Xuất kho cho order 4 - Cupcake',          4),  -- transaction_id=2

-- PXK-005: order 5 (DONE) — xuất Cheesecake lô 6
(14, 6, 'EXPORT',  5, now(), 'Xuất kho cho order 5 - Cheesecake',       5),  -- transaction_id=3

-- PXK-006: order 6 (DONE) — xuất Croissant lô 7 [SỬA: thêm mới]
(15, 7, 'EXPORT',  8, now(), 'Xuất kho cho order 6 - Croissant',        6);  -- transaction_id=4

-- Lưu ý: order 1 & 2 chưa có EXPORT transaction vì receipt còn DRAFT
-- Lưu ý: order 7 & 8 chưa có EXPORT transaction vì receipt còn DRAFT

-- =============================
-- ORDER DETAIL FILL
-- =============================
INSERT INTO order_detail_fill(order_detail_id,batch_id,quantity,created_at) VALUES
-- order 2 (PROCESSING): order_detail_id=3, cần 6 Tiramisu → lấy từ lô 3
(3, 3, 6,  now()),  -- fill order_detail 3 (order 2, Tiramisu qty=6) từ lô 3 ← [SỬA: thêm mới theo flow]

-- order 3 (DISPATCHED): order_detail_id=4, cần 10 Matcha Cake → lấy từ lô 4
(4, 4, 10, now()),  -- fill order_detail 4 (order 3, Matcha Cake qty=10) từ lô 4

-- order 4 (DELIVERING): order_detail_id=5, cần 20 Cupcake → lấy từ lô 5
(5, 5, 20, now()),  -- fill order_detail 5 (order 4, Cupcake qty=20) từ lô 5

-- order 5 (DONE): order_detail_id=6, cần 5 Cheesecake → lấy từ lô 6
(6, 6, 5,  now()),  -- fill order_detail 6 (order 5, Cheesecake qty=5) từ lô 6

-- order 6 (DONE): order_detail_id=7, cần 8 Croissant → lấy từ lô 7
(7, 7, 8,  now());  -- fill order_detail 7 (order 6, Croissant qty=8) từ lô 7

-- order 7 (PROCESSING): order_detail_id=8, cần 12 Strawberry Cake
-- FEFO: lô 1 (expiry 03-05) hết hạn rồi → dùng lô 8 (expiry 03-23, đang PROCESSING)
-- Nhưng lô 8 status=PROCESSING (chưa sản xuất xong) → CHƯA CÓ trong inventories
-- → Thực tế không thể fill từ lô chưa nhập kho
-- → Tạm fill NULL hoặc để hệ thống chờ, ở đây insert với batch khả dụng gần nhất
-- Lô 1 expiry 2026-03-05 < ngày hiện tại 2026-03-09 → ĐÃ HẾT HẠN, không dùng được
-- → order 7 bị tình trạng: KHÔNG ĐỦ HÀNG để fill ← cần chú ý nghiệp vụ

-- =============================
-- QUALITY FEEDBACKS
-- =============================
INSERT INTO quality_feedbacks(order_id,rating,comment,created_at) VALUES
(5, 5, 'Great quality, very fresh!', now()),  -- feedback cho order 5 (DONE) ✅
(6, 4, 'Good cake, will order again', now()); -- feedback cho order 6 (DONE) ✅
-- [SỬA] Xóa feedback của order 3 (status=DISPATCHED, chưa giao xong, không thể feedback)

-- =============================
-- REPORTS
-- =============================
INSERT INTO reports(report_type,user_id,created_date) VALUES
('SALES',       1, now()),  -- report_id=1: Admin tạo báo cáo doanh số
('INVENTORY',   2, now()),  -- report_id=2: Manager tạo báo cáo tồn kho
('PRODUCTION',  2, now()),  -- report_id=3: Manager tạo báo cáo sản xuất
('DELIVERY',    1, now());  -- report_id=4: Admin tạo báo cáo giao hàng

COMMIT;

/*=========================================================================================================*/
/*=========================================================================================================*/
/*=============================================ADDING MOCK DATA============================================*/
/*=========================================================================================================*/
/*=========================================================================================================*/
